export const emojieLibrary = [
  {
    Genre: 'Action',
    Emoji: '🧨',
    id: 1,
    GenreId: 28,
    isSelected: false,
  },
  {
    Genre: 'Adventure',
    Emoji: '💎',
    id: 2,
    GenreId: 12,
    isSelected: false,
  },
  {
    Genre: 'Animation',
    Emoji: '🦁',
    id: 3,
    GenreId: 16,
    isSelected: false,
  },
  {
    Genre: 'Comedy',
    Emoji: '🤣',
    id: 4,
    GenreId: 35,
    isSelected: false,
  },
  {
    Genre: 'Crime',
    Emoji: '🚔',
    id: 5,
    GenreId: 80,
    isSelected: false,
  },
  {
    Genre: 'Factual Film',
    Emoji: '🎥',
    id: 6,
    GenreId: 99,
    isSelected: false,
  },
  {
    Genre: 'Drama',
    Emoji: '🎭',
    id: 7,
    GenreId: 18,
    isSelected: false,
  },
  {
    Genre: 'Family',
    Emoji: '👨‍👩‍👧',
    id: 8,
    GenreId: 10751,
    isSelected: false,
  },
  {
    Genre: 'Fantasy',
    Emoji: '🦄',
    id: 9,
    GenreId: 14,
    isSelected: false,
  },
  {
    Genre: 'History',
    Emoji: '⏳',
    id: 10,
    GenreId: 36,
    isSelected: false,
  },
  {
    Genre: 'Horror',
    Emoji: '🔪',
    id: 11,
    GenreId: 27,
    isSelected: false,
  },
  {
    Genre: 'Music',
    Emoji: '🎧',
    id: 12,
    GenreId: 10402,
    isSelected: false,
  },
  {
    Genre: 'Mystery',
    Emoji: '🔎',
    id: 13,
    GenreId: 9648,
    isSelected: false,
  },
  {
    Genre: 'Romance',
    Emoji: '😍',
    id: 14,
    GenreId: 10749,
    isSelected: false,
  },
  {
    Genre: 'Science Fiction',
    Emoji: '👽',
    id: 15,
    GenreId: 878,
    isSelected: false,
  },
  {
    Genre: 'Thriller',
    Emoji: '😱',
    id: 16,
    GenreId: 53,
    isSelected: false,
  },
];
